name: PR Build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
#        os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: 'Cache: .nuke/temp, ~/.nuget/packages'
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Nuke CI
        shell: pwsh
        run: ./build_nuke.ps1
        env:
          NUKE_GIT_USERNAME: github-actions[bot]
          NUKE_GIT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}